import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ProgressProviders } from "@/lib/progress-providers";
import { TooltipProvider } from "@/components/ui/tooltip"
import { Providers } from "@/lib/providers";
import { Toaster } from "@/components/ui/sonner";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Siroojuddin Apendi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${jakartaSans.className} antialiased`}
      >
        <ProgressProviders>
          <Providers>
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </Providers>
        </ProgressProviders>
        <Toaster/>
      </body>
    </html>
  );
}
